### ISSUE TITLE
harness create more than once produces ??? should be illegal

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#110] opened 2018-12-22 23:47 UTC
`harness add <some-json-file>`
`harness add <some-json-file>`

With the same file and engineId should fail. It seems to update, should report that a harness update is requied.

**Comment by pferrel** [comment] 2018-12-22 23:48
"did you mean to `harness update`?"

**Comment by andreyshikov** [comment] 2020-01-14 11:52
is a duplicate of #124

**Closed as completed by andreyshikov** 2020-01-14 11:52 UTC
Labels: enhancement
